### ISSUE TITLE
Omnipay

### ISSUE THREAD

**Issue by RichardLindhout** [amsgames/laravel-shop#1]
Hey this package looks really cool!

Maybe you should consider to make it compitable with https://github.com/thephpleague/omnipay.

You can connect to a lot of gateways with the sami API!

**Comment by amostajo** [comment]
Wow!

I for sure should check on this.

**Comment by amostajo** [comment]
Well... I added Omnipay support to our milestones.

https://github.com/amsgames/laravel-shop/milestones

We'll get this done probably during version 0.3 if someone doesn't do it before.

**Comment by RichardLindhout** [comment]
Nice dude, I look forward to it :+1:

**Comment by amostajo** [comment]
Hey man, Omnipay Gateway is up:
https://github.com/amostajo/laravel-shop-gateway-omnipay
