### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::add()

### ISSUE THREAD

**Issue by kriangsak** [amsgames/laravel-shop#10]
I can't add MyCustomProduct to Cart 
$cart = Cart::current()->add(MyCustomProduct::find(1)); 

It's show error 
Call to undefined method Illuminate\Database\Query\Builder::add()

How to solve it? 
Please help me. (I'm laravel beginner)

Thank you ^^

**Comment by kriangsak** [comment]
I just forgot. I use Sentinel (Sentry) ^^

**Comment by amostajo** [comment]
Look at the closed issues. One of them was related with sentry.

Mayhe you can fork and make the proper changes to use it with sentry.

Regards.
