### ISSUE TITLE
How can I include a new field for transactions table?

### ISSUE THREAD

**Issue by devfelipereis** [amsgames/laravel-shop#12]
Hello!

Some tables have a user id as a owner of that data. In my case, I also need to know another owner(in this case, an event).

I have some events created and I want to sell products for each one. So, for each one, I need to know what I sold and so on. How can I add a new field for transactions table and populate this field.

I know that I need to change the migration file but I don't know the best way to make this field be a part of a insert when a method of this package is executed.

Can you help me? Thank you!

EDIT 1

I just found this code in Amsgames\LaravelShop\Traits\ShopOrderTrait.

``` php
/**
     * Creates the order's transaction.
     *
     * @param string $gateway       Gateway.
     * @param mixed  $transactionId Transaction ID.
     * @param string $detail        Transaction detail.
     *
     * @return object
     */
    public function placeTransaction($gateway, $transactionId, $detail = null, $token = null)
    {
        return call_user_func(Config::get('shop.transaction') . '::create', [
            'order_id'          => $this->attributes['id'],
            'gateway'           => $gateway,
            'transaction_id'    => $transactionId,
            'detail'            => $detail,
            'token'             => $token,
        ]);
    }
```

I guess that it's the place where I need to put my event_id. But of course that I don't want to change this file... So, to do what I need, do I need to override this method? Or do I have another way?

EDIT 2

Now I see that Amsgames\LaravelShop\Models\ShopTransactionModel uses ShopTransactionTrait. So I can override it in my model, right? And override another protected attribute if I need.

I guess that I know what I need to do to have what I want. So, do you have any suggestions? Thanks!

**Comment by amostajo** [comment]
This package already comes with events:
https://github.com/amsgames/laravel-shop#events

Do you need to create new ones?

**Comment by devfelipereis** [comment]
No, when I say event, it's about an event like a concert, a party and so on. 

I have a model called Event with name, date, place, etc.
I want to sell a lot of things in these events.. and to track what is heppening on wich one, I need to set its id as a parent id in the transactions table or another if I need. 

For example: I want to know how many orders I have in the Event with id === 1, how many transactions, how many, etc. 

For now, an User is a owner of a Order. I also want to make an Event(that is a party, concert) a owner of this Order. 

I don't know if is clear enough for you now :)

**Comment by amostajo** [comment]
If you want to add things to the transaction table, you can do it, simple add the fields (database wise) and what ever you need on the Transaction model.

Although based on what you really need, I wouldn't touch the transaction table at all. Actually I would create these to tables:
- **events**: Where to store your events. It could be a ShopItem.
- **event_goodies (or the name of your choice)** : Where to store the things you want to sell in the events. It should be a shopitem and be linked to the event.

Then add the goodie to the cart.

``` php
$cart->add($event_goodie);
```

You can access your event from an order like this:

``` php
$item = $order->items[0]; // Assuming the order only has one item

if ($item->hasObject) {
  // Get the goodie
  $event_goodie = $item->object;
  // Get the event related to the goodie
  $event = $item->object->event;
}
```

**Comment by devfelipereis** [comment]
Yes. I have a table "events" and "products". It's working fine.

But for now, I need to know from wich Event a transaction(or a order) is coming from. For example:

I can get a order using a user ID. Now I want to get a order using a event ID.

How can I insert an event ID with a order?

**Comment by amostajo** [comment]
If you are doing this:

``` php
$event = Event::find($id);

$cart->add($event);
```

Then the event ID in the order should be located as the reference ID property of an item:

``` php
foreach ($order->items as $item) {
    if ($item->hasObject && $item->class == 'Event') {
        $event = $item->object;
        $event->id;
        // Event ID
        $item->reference_id;
        // or
        $item->object->id
    }
}
```

If you need to add filters or static find functions like `Item::findByEvent($id, $user)` then you can include a laravel `scope` or custom `attribute` into the Item model. Read laravel's documentation for this.

**Comment by devfelipereis** [comment]
Hm.. I guess I'm confusing you. Let me explain about my system for you.

I'm building an event platform where users can create events like a party, concert,lectures etc.

It's everything working good but I still have a lot of things to do. One of this things is create a shop for it.
When a User creates an Event, I'll let the User sell stuff while the Event is happening. 

For this, I found your package perfect for my needs. What I need to do?
- Create products and these products will have an Event as its parent
- Users can buy products from Events

And I can do this with your package, its everything amost perfect. But what I have and what I need?

I have a User that can buy a Product(I created a model for products and I made it shoppable). Fine!

Now I need a different approach. An Order has a User as its owner and it's great.. I can find all the orders of a particular User and do a lot of things with your package methods.

But now, I also want to get all the orders of an Event but keepping the User as an owner of the order. Cause the Product belongs to an Event and a User can buy a Product, when a order is generated, my user will be owner of that... and my Event also need to have a reference for that order. 

So, I want to get all the orders from an Event to track information. But, for example, an Order doen't have an Event ID, it just has the User ID. I want to insert the Event ID that is the parent of the product, with the order in the database.

So later, I could get all the orders generated in a particular Event. Or I could do the same with transactions and know all transactions generated inside an Event, count, check wich Event has more transactions and so on.

Really sorry if I'm taking your time and if I didnt understand your ideia. But I just need this to go ahead and  this need to be done carefully.

Thank you!

**Comment by amostajo** [comment]
As suggested before, simply add a `laravel scope`, in this case to the **Order Model**, so you can do something like this:

``` php
$orders = Order::whereEvent($eventId)->get();
```

I suggest you to read about it in Laravel's documentation, but ideally it should look something like this:

``` php
protected function scopeWhereEvent($query, $eventId)
{
    $productClass = 'App\EventProduct'; // The name of your product model, including namespace.
    return $query->select([DB::raw('orders.*')]) // To get only order information
        ->join('items', function($join) use(&$productClass) {
            $join->on('items.order_id', '=', 'orders.id')
                ->on('items.class', '=', $productClass);
        }) 
        ->join('product_db_table', 'product_db_table.id', '=', 'items.reference_id')
        ->where('product_db_table.event_id', $eventId);
}
```

Make the proper changes according to your needs. Also, I don't know if I have php errors there, fix them and make the function run, but at least you have an idea of what to do.

You can simplify the query by adding an `event_id` model to the **Item Model** and overriding the `add` function in cart so it adds the event ID on record. What ever is easier for you.

EDIT: Add group by to the scope too:

``` php
protected function scopeWhereEvent($query, $eventId)
{
    $productClass = 'App\EventProduct'; // The name of your product model, including namespace.
    return $query->select([DB::raw('orders.*')]) // To get only order information
        ->join('items', function($join) use(&$productClass) {
            $join->on('items.order_id', '=', 'orders.id')
                ->on('items.class', '=', $productClass);
        }) 
        ->join('product_db_table', 'product_db_table.id', '=', 'items.reference_id')
        ->where('product_db_table.event_id', $eventId)
        ->groupBy('orders.id');
}
```

**Comment by devfelipereis** [comment]
Now I'm understanding how to use laravel scopes. I'm not expert and I need to study more.
I'll try this tomorrow and make a scope based on this one.

"You can simplify the query by adding an event_id model to the Item Model and overriding the add function in cart so it adds the event ID on record. What ever is easier for you."

This is what I want to do. I was thinking if I could put the event_id in the transactions or orders table. So I could query them easily. Get all order by the event_id for example.

Thank you so much for help me!

**Comment by amostajo** [comment]
Cool!

If you end up adding the event_it, do it on the **Item Model**, not the **Transaction Model** though. imo.

Glad I was of help.
Regards.
