### ISSUE TITLE
ShopUserTrait' not found

### ISSUE THREAD

**Issue by Siddharth-chauhan** [amsgames/laravel-shop#15]
Getting this error when moved to server from local
http://starsearchproductions.com/shop

Below is code in Model
namespace App;

use Illuminate\Database\Eloquent\Model;
Use Amsgames\LaravelShop\ShopUserTrait;

class Product extends Model {

```
 use ShopUserTrait;
```

**Comment by amostajo** [comment]
I think is a matter of just naming the folders with initial Character in mayus, this might affect Linux based servers. 

I will release an update for this soon. Thanks for the finding

**Comment by amostajo** [comment]
Latest release should fix this. Folders have been renamed to avoid Linux issues.
