### ISSUE TITLE
Session::get retrieves wrong index for gatewayKey

### ISSUE THREAD

**Issue by muratunal** [amsgames/laravel-shop#16]
I'm amused with your code here and thank you some much for your precious effort. That has teached me a lot. I have some questions about some minor issues with kind regards.

The gateway system pushes gatewayKey to the tail of an session key (as an array). However if, you attempt to pay with  multiple gateway and unsuccessfull payment, wrong index returns since getGateway method returns the  the first index of the array. 

What would you prefer us to use instead? Session::put? Perhaps some users might be interested to store the data of attempted unsuccessful gateways. 

Would you prefer pushing data  to the head of array

As an example;

First try:
-Payu
Second try:
-Payu
-Payu(no limit)
Third try:
-bank-transfer
-Payu(no limit)
-Payu(no limit)

**Comment by amostajo** [comment]
You are right about the tail thing. Session::get should retrieve the tail in this case.

Failed and success transactions should be stores at transactions table. On success ones are being stored atm, but I guess you are right about having the history of this.

**Comment by amostajo** [comment]
Changes added on this [commit](https://github.com/amsgames/laravel-shop/commit/4cc2188ea16aaaa05a883be8ffdf70140373c093).

`getGateway` now returns the tail and not the head.

Failed transactions are stored in the transactions table. Can be accessed like:

``` php
$order->transactions;
```

Regards.

**Comment by epigrian** [comment]
@amostajo  Thank you for your effort on this enhancement. Kind Regards (written on behalf of @muratunal)
