### ISSUE TITLE
I Payment via email

### ISSUE THREAD

**Issue by devfelipereis** [amsgames/laravel-shop#25]
I can make payments to my account using this package and works great, but I want to change who I'll pay on the fly using email. Is it possible? Thank you!

**Comment by amostajo** [comment]
You can create a custom payment gateway for this.

**Comment by devfelipereis** [comment]
In fact I want to use paypal. My question was not good enough... I'm using paypal that comes with this package and I it's working. Now I'll receive all payments but I want to chance who will receive the payment on the fly. Is it possible with this package or do I need to use Paypal SDK to get this functionality? Thank you!!

**Comment by amostajo** [comment]
The PayPal gateway uses the PayPal SDK. Again, you can create a custom
gateway to handle your payment process as pleased
