### ISSUE TITLE
Is this package development dead?

### ISSUE THREAD

**Issue by paper9oll** [amsgames/laravel-shop#38]

**Comment by manoj10029** [comment]
when I use this method  Cart::current() I got following error.
This method work properly  $cartUser = Cart::findByUser($user->id);

Integrity constraint violation: 1048 Column 'user_id' cannot be null (SQL: insert into `shpc_cart` (`user_id`, `updated_at`, `created_at`) values (, 2016-02-28 13:18:48, 2016-02-28 13:18:48))

**Comment by phillipmadsen** [comment]
??

**Comment by amostajo** [comment]
Sorry guys, had a lot of workload these months. I will resume this project next month, main goals:
- Coupons
- Laravel 5.2 support.

**Comment by phillipmadsen** [comment]
great!!
