### ISSUE TITLE
problem with item name and item url

### ISSUE THREAD

**Issue by ITwrx** [amsgames/laravel-shop#6]
first of all, let me say, this project looks like it is the exact feature set i was hoping for, especially the good common sense, model conversion feature. so thanks a lot!

I'm using laravel 5.1
i converted an existing model to use with laravel-shop.
i can add it to the cart and view the cart but 

```
<a href="{{ $item->shopUrl }}">{{ $item->displayName }}</a> 
```

only outputs 

```
<a href="#"></a>
```

however, i notice that everything that comes directly from the items table is output sucessfully. the top of the converted model in question is:

```
 namespace App\Models;

use Amsgames\LaravelShop\Traits\ShopItemTrait;
use Illuminate\Database\Eloquent\Model;

class Paso extends Model {

    use ShopItemTrait;

    /**
     * Name of the route to generate the item url.
     *
     * @var string
     */
    protected $itemRouteName = 'paso_finos';

    /**
     * Name of the attributes to be included in the route params.
     *
     * @var string
     */
    protected $itemRouteParams = ['slug'];

```

the name attribute in my model's table is "name" and i also tried

```
protected $itemName = 'product_name';
```

in my model to no avail. 

I can also add the cart to an order but it looks like paypal chokes on the lack of item name, so i'm hoping this fixes that too.

Any ideas?

Thanks in advance

**Comment by amostajo** [comment]
Sorry for this late answer.

Sounds like your cart/order items are not being related to your "Paso" class.

Please, check these 2 things:
- In the DB, `items` table, look for the items with the issue and check the value for columns `class` and `referenceId`. You should have the values `App\Models\Paso` and `#id`.
- Double check that you are adding the whole object to the cart and not just an array with the _SKU_ and _price_ indicated.

**Comment by ITwrx** [comment]
That's exactly what the problem was. I completely forgot that i had had problems adding the whole object and was only adding the sku and price as a temp hack. Now the item url and name are being echo'd. Thanks a lot! 
i'm still getting 

```
ErrorException in GatewayPayPalExpress.php line 142: Undefined property: stdClass::$name

```

but i'll get back on that with new issue if i can't find anything on my end over the next day or so. Thanks.

**Comment by amostajo** [comment]
Have you configured your PayPal settings?

https://github.com/amsgames/laravel-shop-gateway-paypal#configuration

**Comment by ITwrx** [comment]
yes, and i see this $name error must be preceeded by a paypal connection error. my paypal sandbox creds are good but i'm developing and testing from localhost so i'm guessing that's the underlying problem. Thanks

**Comment by amostajo** [comment]
I've done testing from localhost and it works fine. Make sure you have setup sandbox properly and that you developer account is correctly configured in PayPal's developer panel.

**Comment by ITwrx** [comment]
I misunderstood what was required with paypal settings. I had my sandbox biz creds instead of paypal developer app creds in laravel-shop-gateway-paypal config! Also, I didn't know i needed to create api app in paypal developer at all. now laravel-shop works great! 

If you wanted to "dummy-proof+" the laravel-shop-gateway-paypal docs you could prepend the current authentication section with something like "first create an api app in your paypal developer account ..."

one question though, if you don't mind. paypal returns to my app's return url with "?order=12" appended to the url. how do i parse this as $orderId/{orderId} in my routes.php so i can show results of just this order? Or maybe there is a way to have it come back appended with "/12" (assuming 12 is order id)?

Thanks again. you've really taken the pain out of creating a custom shop w paypal.

**Comment by amostajo** [comment]
Thanks for the suggestion. Will add that "dummy-proof" message.

In regards to the callback. You can change the route name of the order page the shop will open in return, this is explained in the [gateway's page](https://github.com/amsgames/laravel-shop-gateway-paypal#configuration-1); change this on `config/shop.php`.

You can easily setup your order's page with a **wildcard** to accomplish what you are looking for:

``` php
Route::get('order/{order}', ['as' => 'orderpage', 'uses' => 'OrderController@show']);
```

Then in your controller have something like:

``` php
public function show($order)
{
  $order = Order::find($order);

  // Do what ever you want here
  return view('order', ['order' => $order]);
}
```

**Off topic:** There is a new gateway that allows you to connect the shop to more payment services, like Stripe, 2checkout, Authorize.net.. etc:
https://github.com/amostajo/laravel-shop-gateway-omnipay

**Comment by ITwrx** [comment]
Thanks. I have the wildcard in route and controller already and callback_redirect_route in shop.php

```
//routes.php

Route::get('/account/order-status/{orderId}', array('as' => 'order_status', 'uses' => 'AccountController@getOrder_status'));
```

```
//AccountController.php
public function getOrder_status($orderId)
```

```
//shop.php
'callback_redirect_route' => 'order_status',
```
but the order comes back with "?order=12" instead of "/12" at thge end of the url and therefore doesn't match my route. What am i missing?

**Comment by ITwrx** [comment]
everything works! i just needed to clear route cache and try again. thanks for your help.

RE: omnipay. Wow. that's cool. didn't know about that. thanks.
