### ISSUE TITLE
subscription/recurring payment item

### ISSUE THREAD

**Issue by ITwrx** [amsgames/laravel-shop#9]
hi,
is there a way to create a product/item to use with laravel-shop that uses s subscription or recurring payment instead of one time payment? 

thanks in advance.

**Comment by amostajo** [comment]
This package does not provide psroduct solution yet, so you are free to develop the product as you please. 

You will have to code this from scratch though.

**Comment by ITwrx** [comment]
Thanks for your response. I understand that i am responsible for the product models and have several of them working well already. These are all added to the cart as "buy now" type single purchase/payment items. That use case is covered in your docs. I'm just not sure about how i'm supposed to add a product to the cart in such a way that paypal gateway and subsequently paypal will know it's a subscription instead of single purchase. For instance, there is no "is_recurring" column in items table for me to fill so that when that item is in the cart paypal gateway knows it's a subscription. What is the general procedure or other requirements for adding a subscription to a cart and paying for it using laravel-shop with laravel-shop-paypal-gateway? Are modifications to laravel-shop or the paypal gateway required? Or it's already quite possible to do and i just don't see how? Thanks again.

**Comment by amostajo** [comment]
PayPal express and direct credit card doesn't have a is recurring parameters as far as I know. 

What I would do is the following:

1) Use direct credit card payment gateway (paypal). 

2) Add the is_recurring property to your item table. 

3) Add a feature to save user credit cards (you should encrypt this information though in case your software is hacked for some reason). 

4) Create a daily Laravel command that check on recurring product dates and rules. This command should create an automated payment of the subscription (should create an order and process it). 

That is what I would do.  The other would be to check if PayPal has an option, of it does, let me know so we can add a feature issue to include this type of gateway.

**Comment by ITwrx** [comment]
Thanks again. I'll look into that.

**Comment by ITwrx** [comment]
Unless express checkout is different from paypal express, it seems subscription/recurring payments is available. When i do a search for "subscriptions with paypal express" @ startpage.com i get many seemingly relevant results. One of which is:

https://developer.paypal.com/docs/classic/express-checkout/ht_ec-recurringPaymentProfile-curl-etc/

It would be great if this feature was added to laravel-shop and for my use case it is more important than other roadmap features.

Thanks in advance.

**Comment by amostajo** [comment]
It should be done using PHP SDK, but yeah, though seems like there is an option there too.

The feature should be added to PayPal gateway package page, please request the feature [here](https://github.com/amsgames/laravel-shop-gateway-paypal).

I'll check it out when I am free (not soon though, we are working on projects). If you are in seriously on need for this, I invite you to develop the gateway for this, if not, you'll have to wait until the feature is added.

Hope this helps.

**Comment by ITwrx** [comment]
sure, i'll request it there. I don't know if i'll be able to develop the feature or not but i'll take a look if i get time. I understand busy, as well. Thanks for the help.
